# Change these first
owner: HexaGhost-09 # Your GitHub organization or username, where this repository lives
repo: Uptime-Status # The name of this repository

sites:
  - name: LinksPlace
    url: https://linksplace.vercel.app
  - name: Byte Notes Blog
    url: https://byte-notes-blog.vercel.app
  - name: Nova Repacks Website
    url: https://nova-repacks.vercel.app
  - name: Trim URL Eight Website
    url: https://trim-url-eight.vercel.app
  - name: Status Watch LOL
    url: https://status-watch-lol.vercel.app
  - name: TinyURL Server
    url: https://tinyurl-server.deno.dev
    
status-website:
  cname: hexaghost-09.github.io/Uptime-Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime-Status
  introTitle: "**Uptime-Status** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/HexaGhost-09/Uptime-Status). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/HexaGhost-09/Uptime-Status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
